### ISSUE TITLE
[Question] Stock RNE 

### ISSUE THREAD

**Issue by omar6995** [annuaire-entreprises-data-gouv-fr/search-infra#275]
Bonjour Messieurs,

Je voulais tout d'abord vous féliciter pour le travail réalisé  ! Je travaille sur un projet perso et cette bibliothèque de DAG est un très bon point de départ pour moi.

J'avais une question concernant le stock RNE dont vous parlez [ici](https://github.com/etalab/annuaire-entreprises-search-infra/tree/main/workflows/data_pipelines/rne/stock)

Je suis licencié à l'INPI , j'ai bien accès au serveur SFTP mais je n'y trouve que les informations sur les actes et les bilans.

Pour les informations sur les dirigeants, celles ci ne sont disponible que depuis l'API et je n'ai le droit qu'a 10 000 calls / jour.... 

Je voulais savoir si vous disposez d'un accès specifique? ou si vous avez l'adresse du serveur FTP ? 

De mon coté, j'ai les accès sur les serveurs SFTP suivants :
 
-registre-national-entreprises.inpi.fr
-www.inpi.net
 
Cependant les 2 n'hebergent que les actes et les bilans...

Les personnes gérant la boite mail licence@inpi ne sont pas très réactif et toute mes relances restent sans réponse :/

Par avance, merci pour votre aide !

**Comment by HAEKADI** [comment]
Bonjour Omar,

Merci pour votre retour.

Nous disposons des mêmes accès à l'API RNE et sommes soumis aux mêmes restrictions que vous, en termes de nombre d'appels par adresse IP par jour.

Concernant l'accès au stock, nous avons récupéré les données en septembre 2023 via le SFTP. Il est possible que les serveurs de l'INPI connaissent des instabilités en ce moment, ce qui pourrait expliquer pourquoi vous ne parvenez pas à accéder directement aux fichiers de stock.

Excellente journée,

Hajar
