### ISSUE TITLE
[OPENDATA]Publication quotidienne des données de notre base de données sur data.gouv.fr au format Parquet

### ISSUE THREAD

**Issue by geoffreyaldebert** [annuaire-entreprises-data-gouv-fr/search-infra#325]
- publier sur data.gouv.fr des csvs enrichis des données récupérées de l'annuaire
- parquet si possible

**Comment by HAEKADI** [comment]
cc @XavierJp

**Comment by XavierJp** [comment]
Concernant les donnees 

Je me demande si on a pas interet a publier l'adresse agrégée et la denomination calculee

**Comment by XavierJp** [comment]
Ainsi que les deux dates inscription insee et inscription inpi

**Comment by HAEKADI** [comment]
Publication au format CSV. Le format Parquet est trop complexe à gérer pour le moment en raison de la taille des données. Il est impossible de concaténer des fichiers Parquet sans les lire en entier, ce qui entraîne des problèmes de performance significatifs (mémoire et temps).
