### ISSUE TITLE
[Organisation] whitelisting de l'urssaf et blacklisting de la RATP

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/search-infra#416]
Actuellement dans l’API :  
- la RAPT est considérée comme un service public
- les urssaf de région ne le sont pas

Le pôle juridique nous autorise à changer cela et ouvrir par la même occasion les accès agents aux membres des urssafs.

**Comment by HAEKADI** [comment]
https://open.urssaf.fr/explore/dataset/liste-des-sites-et-des-activites/table/

**Comment by HAEKADI** [comment]
La [liste](https://fichierdirect.declaration.urssaf.fr/TablesReference.htm) utilisée.

D'après la [description](https://www.urssaf.org/accueil/l-urssaf/notre-organisation-et-gouvernanc/une-organisation-en-reseau.html), il existe 26 Urssaf dans le réseau. Le csv contient 27 siren distincts.
