### ISSUE TITLE
[Data] Extrait de donnée RNE/INSEE

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/search-infra#417]
Trois extraits : 

Les Sociétés Civiles Agricoles (la suite), la requête serait :

• Forme juridique au répertoire SIRENE = 6597
• Forme juridique au RCS = « Société Civile Agricole »
• Société active

Les EARL :

• Forme juridique au répertoire SIREN = 2900
• Dénomination entité SIRENE contient EARL
• Société active

Les GFA :

• Forme juridique au répertoire SIREN = 2900
• Dénomination entité SIRENE contient GFA
• Société active

Les champs de sortie : 
siren, dénomination sirene, code NAF

**Comment by HAEKADI** [comment]
* Sociétés Civiles Agricoles : count **45387**
[extract_sociétés_civiles_agricoles.txt](https://github.com/user-attachments/files/17681186/extract_societes_civiles_agricoles.txt)

**Comment by XavierJp** [comment]
Aouch 45000 je vais en baver !

**Comment by hacherix** [comment]
Requête GFA:
```
select siren, nom_raison_sociale, activite_principale_unite_legale
from main.unite_legale
where
    from_insee = true
    and nom_raison_sociale like '%GFA%'
    and nature_juridique_unite_legale = 2900
    and date_fermeture_unite_legale is not null;
```
[export_gfa.csv](https://github.com/user-attachments/files/17728544/export_gfa.csv)
Count: 76

Requête EARL:
```
select siren, nom_raison_sociale, activite_principale_unite_legale
from sirene.unite_legale
where
    from_insee = true
    and nom_raison_sociale like '%EARL%'
    and nature_juridique_unite_legale = 2900
    and date_fermeture_unite_legale is not null;
```
[export_earl.csv](https://github.com/user-attachments/files/17728543/export_earl.csv)
Count: 22

@HAEKADI Tu peux valider les requêtes ? De mémoire tu avais fait autrement pour avoir les unités actives non ?

**Comment by HAEKADI** [comment]
@hacherix J'utilise `etat_administratif_unite_legale = "A"`.  [Voici](https://sirene.fr/static-resources/htm/v_sommaire_311.htm) la liste des variables Sirene pour expliquer la valeur.

La variable de date de fermeture est un peu plus complexe et bug prone, je préfère donc utiliser celle-ci.

Sinon, it looks good to me 😄 

@XavierJp est-ce que tu préfères du .txt ou le .csv passe aussi ?
