### ISSUE TITLE
[BUG]Convention collective metadata indisponible

### ISSUE THREAD

**Issue by HAEKADI** [annuaire-entreprises-data-gouv-fr/search-infra#418]
DAG [get_metadata_cc](https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/tree/main/workflows/data_pipelines/metadata/cc).

**Comment by hacherix** [comment]
Le retour au mois précédent en cas d'erreur de téléchargement du fichier était impossible car les fichiers n'étaient pas conservés sur le endpoint.
A la place, nous avons décidé d'améliorer la notification du fichier manquant avec un message de ce type :
```
🔴 Get_Metadata_Cc: Données 
 - create_metadata_concollective_json(failed): ⚠️ 404: Le fichier CC du DARES n'est pas disponible depuis 56 jours.
```
Ainsi nous n'enquêterons sur ce problème connu que lorsque nous pensons que cela est vraiment nécessaire.

J'en ai également profité pour refactor le code des notifications pour faciliter à l'avenir l'enrichissement des messages.

Cependant après une nouvelle investigation j'ai découvert que l'URL utilisée par la DARES avait changé, voici donc la nouvelle. Le code a été changé en fonction.
https://travail-emploi.gouv.fr/sites/travail-emploi/files/2024-11/Dares_donnes_Identifiant_convention_collective_Novembre24.xlsx
